name: flag
description: A flag Flutter package. Use for showing flags. All flags came from https://www.un.org/en/member-states/index.html . 
version: 4.0.0
homepage: https://github.com/LunaGao/flag_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.21.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/flag/
